football:
  target_col: home_win
  features:
    - home_form_5
    - away_form_5
    - home_goals_avg
    - away_goals_avg
    - diff_classement
    - odds_home
    - odds_draw
    - odds_away

tennis:
  target_col: player1_win
  features:
    - rank_diff
    - surface_hard
    - surface_clay
    - surface_grass
    - form_10_p1
    - form_10_p2
    - h2h_p1_wins
    - fatigue_p1

basketball:
  target_col: home_win
  features:
    - points_avg_home
    - reb_avg_home
    - eff_rating_home
    - back_to_back
    - spread
    - points_avg_away
    - reb_avg_away
    - eff_rating_away



football:
  features:
    - home_form
    - away_form
    - home_rank
    - away_rank
    - home_odds
    - away_odds
    - home_advantage

tennis:
  features:
    - player1_rank
    - player2_rank
    - player1_form
    - player2_form
    - surface_clay
    - surface_grass
    - head_to_head

basketball:
  features:
    - home_form
    - away_form
    - home_ppg
    - away_ppg
    - pace
    - home_odds
    - away_odds
